config/routes.rb
Rails.application.routes.draw do
  get 'cats/index'

  root 'cats_infos#index'
  resources :cats_infos

end

app/models/cat_db.rb
class CatDb < ActiveRecord::Base
	validates :name, presence: true
	has_attached_file :picture , styles: {thumb: "150x150#"}
	do_not_validate_attachment_file_type :picture

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
  end
 end

app/controllers/cats_infos_controller.rb
class CatsInfosController < ApplicationController
	#http_basic_authenticate_with name: "qvantel", password: "qvantelpassword", except: [:index, :show]
	def new
		@cats_info = CatDb.new
	end

	def edit
		@cats_info = CatDb.find(params[:id])
	end	

	def create
		@cats_info = CatDb.new(cats_params)
		if @cats_info.save
			@cats_infos = CatDb.all
			render :index
		else
			render :new
		end
	end

	def update
		@cats_info = CatDb.find(params[:id])
		if @cats_info.update(cats_params)
			redirect_to :action => 'show'
		else
			render :edit
		end
	end
	def index
		@cats_infos = CatDb.all
	end
	def show
		@cats_infos = CatDb.find(params[:id])
	end
	def destroy
		@cats_info = CatDb.find(params[:id])
		@cats_info.delete
		redirect_to cats_infos_path
	end
	
	private
  		def cats_params
  			params.require(:cats_info).permit(:name, :color, :picture, :race, :gender, :details)
  		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/cats_infos_helper.rb
module CatsInfosHelper
end

app/views/cats/index.html.erb
<h1>Cats index</h1>

app/views/cats_infos/_form.html.erb
<%= form_for :cats_info  do |f| %>

<% if @cats_info.errors.any? %>
	<div id="error">
		<div>
			<%= pluralize(@cats_info.errors.count, "error") %> found, please adjust incorrect field contents
		</div>
		<ul>
			<% @cats_info.errors.full_messages.each do |msg|%>
			<li>
				<%= msg %>
			</li>
			<%end%>
		</ul>
	</div>
<% end %>

	<p>
		<%= f.label :name%><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :color %><br>
		<%= f.text_field :color %>
	</p>

	<p>
		<%= f.label :picture %><br>
		<%= f.text_field :picture %>
	</p>

	<p>
		<%= f.label :race %><br>
		<%= f.text_field :race %>
	</p>

	<p>
		<%= f.label :gender %><br>
		<%= f.text_field :gender %>
	</p>

	
	<p>
		<%= f.label :details %><br>
		<%= f.text_area :details %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>


app/views/cats_infos/edit.html.erb
	<div class="container">
	<h2>Edit your cat info here</h2><br/>

		<div class="row">
			<div class="col-md-5">
				<%= form_for :cats_info, url: cats_info_path(@cats_info), method: :patch do |f| %>

					<% if @cats_info.errors.any? %>
					<div id="error">
						<div>
							<%= pluralize(@cats_info.errors.count, "error") %> found, please adjust incorrect field contents
						</div>
						<ul>
							<% @cats_info.errors.full_messages.each do |msg|%>
							<li>
								<%= msg %>
							</li>
							<%end%>
						</ul>
					</div>
				<% end %>

					<p>
						<%= f.label :name%><br>
						<%= f.text_field :name , class: 'form-control'%>
					</p>

					<p>
						<%= f.label :color %><br>
						<%= f.text_field :color, class: 'form-control' %>
					</p>

					<p>
						<%= f.label :picture %><br>
						<%= f.file_field :picture , class: 'form-control'%>
					</p>

					<p>
						<%= f.label :race %><br>
						<%= f.select(:race, options_for_select([['Abyssinian', 'Abyssinian'], ['Aegean', 'Aegean'], ['American Bobtail', 'American Bobtail'], ['American Shorthair', 'American Shorthair'], ['American Wirehair', 'American Wirehair'], ['Arabian Mau', 'Arabian Mau'], ['Australian Mist', 'Australian Mist'], ['Asian', 'Asian'], ['Asian Semi-longhair', 'Asian Semi-longhair'], ['Brazilian Shorthair', 'Brazilian Shorthair'], ['Devon Rex', 'Devon Rex'], ['Dragon Li', 'Dragon Li'], ['Exotic Shorthair', 'Exotic Shorthair'], ['German Rex', 'German Rex']], selected: :race ),{}, { :class => 'form-control' } ) %>

					</p>

					<p>
						<%= f.label :gender %><br>
						<%= f.select(:gender, options_for_select([['Male', 'Male'], ['Female', 'Female']], selected: :gender ),{}, { :class => 'form-control' } ) %>
					</p>

					
					<p>
						<%= f.label :details %><br>
						<%= f.text_area :details , class: 'form-control'%>
					</p>

					<p>
						<%= f.submit  :class => '_custm_btn', :value => "Update" %>
					</p>
				<% end %>
				<br/>
				<div>
					<%= link_to 'Click to see all cats', cats_infos_path %>
				</div>
				</div>
			</div>
		</div>

app/views/cats_infos/index.html.erb
<div>
	<h2> List containing all cats </h2><br/>
	<div class="container">
	<div class="row">
			<div class="col-md-7">
			<div class="titles">
				<div class="container">
					<div class="row">
						<div class="col-sm-3 a">Name</div>
						<div class="col-sm-3 b">Color</div>
						<div class="col-sm-3 c">Gender</div>
						<div class="col-sm-3 d">Race</div>						
					</div>
				</div>
			</div>
			</div>
		</div>
		<% @cats_infos.each do |cats_info| %>

		<div class="row">
			<div class="col-md-7">
					
					<hr/>
					<div >
						<div class="col-sm-3 a"><%= cats_info.name %></div>
						<div class="col-sm-3 b"><%= cats_info.color %></div>
						<div class="col-sm-3 c"><%= cats_info.gender %></div>
						<div class="col-sm-3 d"><%= cats_info.race %></div>
					</div>	
					<div id="details">
						<h4>Details</h4>
						<div><%= cats_info.details %></div>
					</div>
<br/>
					<div class="ctrls">
						<div class="_custm_btns"><%= link_to 'Edit', edit_cats_info_path(cats_info), class: '_custm_btn' %></div>
						<div class="_custm_btns"><%= button_to 'Delete', cats_info_path(cats_info), :method => :delete, data: { :confirm => 'Are you sure?' }, class: '_custm_btn' %></div>
					</div>
					<br/>			
			</div>


				<div class="col-md-3">
						<div><%= image_tag cats_info.picture.url %></div>
				</div>
				<br/>
			
					
			</div>

	</div>
</div>
<hr/>
<% end %>
<div class="container">
	<div class="row">
		<div><%= link_to 'Add a your cat to our database?', new_cats_info_path , class: '_custm_btn2'%></div>
	</div>
</div>



app/views/cats_infos/new.html.erb
<h1>New Cat</h1>
<div class="container">
		<div class="row">
			<div class="col-md-5">
				<%= form_for :cats_info, html: { multipath: true },url: cats_infos_path do |f| %>

				<% if @cats_info.errors.any? %>
					<div id="error">
						<div>
							<%= pluralize(@cats_info.errors.count, "error") %> found, please adjust incorrect field contents
						</div>
						<ul>
							<% @cats_info.errors.full_messages.each do |msg|%>
							<li>
								<%= msg %>
							</li>
							<%end%>
						</ul>
					</div>
				<% end %>

					<p>
						<%= f.label :name%><br>
						<%= f.text_field :name , class: 'form-control'%>
					</p>

					<p>
						<%= f.label :color %><br>
						<%= f.text_field :color , class: 'form-control'%>
					</p>

					<p>
						<%= f.label :picture %><br>
						<%= f.file_field :picture , class: 'form-control'%>
					</p>

					<p>
						<%= f.label :race %><br>
						<%= f.select(:race, options_for_select([['Abyssinian', 'Abyssinian'], ['Aegean', 'Aegean'], ['American Bobtail', 'American Bobtail'], ['American Shorthair', 'American Shorthair'], ['American Wirehair', 'American Wirehair'], ['Arabian Mau', 'Arabian Mau'], ['Australian Mist', 'Australian Mist'], ['Asian', 'Asian'], ['Asian Semi-longhair', 'Asian Semi-longhair'], ['Brazilian Shorthair', 'Brazilian Shorthair'], ['Devon Rex', 'Devon Rex'], ['Dragon Li', 'Dragon Li'], ['Exotic Shorthair', 'Exotic Shorthair'], ['German Rex', 'German Rex']], selected: :race ),{}, { :class => 'form-control' } ) %>
					</p>

					<p>
						<%= f.label :gender %><br>
						<%= f.select(:gender, options_for_select([['Male', 'Male'], ['Female', 'Female']], selected: :gender ),{}, { :class => 'form-control' } ) %>
					</p>

					
					<p>
						<%= f.label :details %><br>
						<%= f.text_area :details , class: 'form-control'%>
					</p>

					<p>
						<%= f.submit :class => '_custm_btn', :value => "Submit" %>
					</p>
				<% end %>

				<%= link_to 'Click to see all cats', cats_infos_path %>
			</div>
		</div>
	</div>

app/views/cats_infos/show.html.erb
<div class="container">
<h2> About <%= @cats_infos.name %></h2><br/>
    <div class="row">
      <div class="col-md-7">
          <p>
            <strong>Name:</strong>
            <%= @cats_infos.name %>
          </p>
           
           <p>
            <strong>Color:</strong>
            <%= @cats_infos.color %>
          </p>
           
           
           
           <p>
            <strong>Gender:</strong>
            <%= @cats_infos.gender %>
          </p>
           
          <p>
            <strong>Race:</strong>
            <%= @cats_infos.race %>
          </p>

          <p>
            <strong>Details:</strong>
            <%= @cats_infos.details %>
          </p>
      </div>
      <div class="col-md-3">
        <p>
            <%= image_tag @cats_infos.picture.url %>
          </p>
        </div>
    </div>
  </div>
   <div class="container">
      <div class="row">
         <div class="._custm_btn col-sm-2"><%= link_to 'Edit', edit_cats_info_path(@cats_infos), :class => '_custm_btn' %></div>
         <br/><div><%= link_to 'View all cats details', cats_infos_path %></div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats Database</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>